// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszGgh3CpkXEQ3jonPGL55ROGjHL-UuHs',
    appId: '1:311712983590:web:9cce88cfbfdd34dc6a14e7',
    messagingSenderId: '311712983590',
    projectId: 'burkaan-inventory-management',
    authDomain: 'burkaan-inventory-management.firebaseapp.com',
    storageBucket: 'burkaan-inventory-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtkQI4iQjwVjOeegn-GgApiS7EJD1h20',
    appId: '1:311712983590:android:2a151ab6efc78ec36a14e7',
    messagingSenderId: '311712983590',
    projectId: 'burkaan-inventory-management',
    storageBucket: 'burkaan-inventory-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_h6Wq-M7VYxsOffCwcOoKP7biMRzhEKI',
    appId: '1:311712983590:ios:774e898169a511b06a14e7',
    messagingSenderId: '311712983590',
    projectId: 'burkaan-inventory-management',
    storageBucket: 'burkaan-inventory-management.firebasestorage.app',
    iosBundleId: 'com.example.kenzProject',
  );

}